server.port=\

spring.datasource.url=jdbc:postgresql://dpg-d9jsik7avr4c73a4r9h0-a.ohio-postgres.render.com:5432/trafico_ndiz
spring.datasource.username=trafico_user
spring.datasource.password=564W7670SpBcTB8C0A948jkUwIKG904X
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

logging.level.com.inmotion.trafico=DEBUG
